"""Initial migration

Revision ID: 2b247683a387
Revises: 7bfef87ad415
Create Date: 2025-10-11 00:36:29.023196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b247683a387'
down_revision = '7bfef87ad415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('id_client',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('id_client',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
