"""Ajout reset_token et reset_token_expiration

Revision ID: cae1f9fa8c06
Revises: 4d56deabcfa8
Create Date: 2025-10-04 21:36:59.281964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae1f9fa8c06'
down_revision = '4d56deabcfa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('avis_id_client_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['id_client'], ['id_client'], ondelete='CASCADE')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('mot_de_passe',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('nombre_personnes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.alter_column('nombre_personnes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('mot_de_passe',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('avis', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('avis_id_client_fkey'), 'clients', ['id_client'], ['id_client'])

    # ### end Alembic commands ###
